src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255)]
    private ?string $transporteurNom = null;

    #[ORM\Column]
    private ?float $transporteurPrix = null;

    #[ORM\Column(length: 255)]
    private ?string $livraison = null;

    #[ORM\Column]
    private ?bool $isPaid = null;

    #[ORM\Column(length: 255)]
    private ?string $methode = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $stripeSessionId = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $paypalCommandeId = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreateAt = null;

    #[ORM\OneToMany(mappedBy: 'Commande', targetEntity: RecapDetails::class)]
    private Collection $recapDetails;


    #[ORM\Column(length: 255)]
    private ?string $adr_fact = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $date_fact = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?Users $com_users = null;

    #[ORM\Column(nullable: true)]
    private ?int $com_fact_id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $facture_total_ttc = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $facture_total_ht = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $facture_tva = null;


    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?Adresse $com_adr_livr = null;

    #[ORM\OneToMany(mappedBy: 'panier_com', targetEntity: Panier::class)]
    private Collection $paniers;




    public function __construct()
    {
        $this->recapDetails = new ArrayCollection();
        $this->paniers = new ArrayCollection();
    }




    public function getId(): ?int
    {
        
        return $this->id;
    }
    



    public function getTransporteurNom(): ?string
    {
        return $this->transporteurNom;
    }

    public function setTransporteurNom(string $transporteurNom): static
    {
        $this->transporteurNom = $transporteurNom;

        return $this;
    }

    public function getTransporteurPrix(): ?float
    {
        return $this->transporteurPrix;
    }

    public function setTransporteurPrix(float $transporteurPrix): static
    {
        $this->transporteurPrix = $transporteurPrix;

        return $this;
    }

    public function getLivraison(): ?string
    {
        return $this->livraison;
    }

    public function setLivraison(string $livraison): static
    {
        $this->livraison = $livraison;

        return $this;
    }

    public function isIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    public function setIsPaid(bool $isPaid): static
    {
        $this->isPaid = $isPaid;

        return $this;
    }

    public function getMethode(): ?string
    {
        return $this->methode;
    }

    public function setMethode(string $methode): static
    {
        $this->methode = $methode;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripeSessionId;
    }

    public function setStripeSessionId(?string $stripeSessionId): static
    {
        $this->stripeSessionId = $stripeSessionId;

        return $this;
    }

    public function getPaypalCommandeId(): ?string
    {
        return $this->paypalCommandeId;
    }

    public function setPaypalCommandeId(?string $paypalCommandeId): static
    {
        $this->paypalCommandeId = $paypalCommandeId;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeImmutable $CreateAt): static
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    /**
     * @return Collection<int, RecapDetails>
     */
    public function getRecapDetails(): Collection
    {
        return $this->recapDetails;
    }

    public function addRecapDetail(RecapDetails $recapDetail): static
    {
        if (!$this->recapDetails->contains($recapDetail)) {
            $this->recapDetails->add($recapDetail);
            $recapDetail->setCommande($this);
        }

        return $this;
    }

    public function removeRecapDetail(RecapDetails $recapDetail): static
    {
        if ($this->recapDetails->removeElement($recapDetail)) {
            // set the owning side to null (unless already changed)
            if ($recapDetail->getCommande() === $this) {
                $recapDetail->setCommande(null);
            }
        }

        return $this;
    }



    public function getAdrFact(): ?string
    {
        return $this->adr_fact;
    }

    public function setAdrFact(string $adr_fact): static
    {
        $this->adr_fact = $adr_fact;

        return $this;
    }

    public function getDateFact(): ?\DateTimeImmutable
    {
        return $this->date_fact;
    }

    public function setDateFact(\DateTimeImmutable $date_fact): static
    {
        $this->date_fact = $date_fact;

        return $this;
    }

    public function getComUsers(): ?Users
    {
        return $this->com_users;
    }

    public function setComUsers(?Users $com_users): static
    {
        $this->com_users = $com_users;

        return $this;
    }

    public function getComFactId(): ?int
    {
        return $this->com_fact_id;
    }

    public function setComFactId(int $com_fact_id): static
    {
        $this->com_fact_id = $com_fact_id;

        return $this;
    }

    public function getFactureTotalTtc(): ?string
    {
        return $this->facture_total_ttc;
    }

    public function setFactureTotalTtc(?string $facture_total_ttc): static
    {
        $this->facture_total_ttc = $facture_total_ttc;

        return $this;
    }

    public function getFactureTotalHt(): ?string
    {
        return $this->facture_total_ht;
    }

    public function setFactureTotalHt(?string $facture_total_ht): static
    {
        $this->facture_total_ht = $facture_total_ht;

        return $this;
    }

    public function getFactureTva(): ?string
    {
        return $this->facture_tva;
    }

    public function setFactureTva(?string $facture_tva): static
    {
        $this->facture_tva = $facture_tva;

        return $this;
    }


    public function getComAdrLivr(): ?Adresse
    {
        return $this->com_adr_livr;
    }

    public function setComAdrLivr(?Adresse $com_adr_livr): static
    {
        $this->com_adr_livr = $com_adr_livr;

        return $this;
    }

    /**
     * @return Collection<int, panier>
     */
    public function getPanier(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(panier $panier): static
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers->add($panier);
            $panier->setPanierCom($this);
        }

        return $this;
    }

    public function removePanier(panier $panier): static
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getPanierCom() === $this) {
                $panier->setPanierCom(null);
            }
        }

        return $this;
    }








}

src/Controller/CommandeCrudController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\Commande1Type;
use App\Service\CartService;
use App\Repository\AdresseRepository;
use App\Repository\CommandeRepository;
use App\Repository\PanierRepository;
use App\Repository\RecapDetailsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/commande/crud')]
class CommandeCrudController extends AbstractController
{
    #[Route('/', name: 'app_commande_crud_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande_crud/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/mesCommandes', name: 'app_commande_mon_index', methods: ['GET'])]
    public function monIndex(CommandeRepository $commandeRepository,CartService $cartService): Response
    {
        
        return $this->render('commande_crud/mycommande.html.twig', [
            'commandes' => $commandeRepository->findBy(['com_users' => $this->getUser()]),
        
        ]);
    }

    
    #[Route('/facture/{id}', name: 'app_commande_facture', methods: ['GET'])]
    public function facture(CommandeRepository $commandeRepository, $id,PanierRepository $repo, AdresseRepository $adresseRepository): Response
    {
        $adrFactId = $commandeRepository->findOneBy(['com_fact_id' => $id])->getAdrFact();
        $comId = $commandeRepository->findOneBy(['com_fact_id' => $id])->getId();
        $createAt = $commandeRepository->findOneBy(['com_fact_id' => $id])->getCreateAt();
        $dateFact = $commandeRepository->findOneBy(['com_fact_id' => $id])->getCreateAt();
        $adrLivrID = $commandeRepository->findOneBy(['com_fact_id' => $id])->getComAdrLivr();
        $adrLivr = $adresseRepository->findOneBy(['id' => $adrLivrID]);
        $adrFact = $adresseRepository->findOneBy(['id' => $adrFactId]);
        $usersId = $commandeRepository->findOneBy(['com_fact_id' => $id])->getComUsers()->getId();
        $factId = $commandeRepository->findOneBy(['com_fact_id' => $id])->getComFactId();
        $prod = $commandeRepository->facture(['id' =>$id]);

        return $this->render('commande_crud/facture.html.twig', [
            'adrFactId' => $adrFactId,
            'comId' => $comId,
            'createAt' => $createAt,
            'dateFact' => $dateFact,
            'adrLivr' => $adrLivr,
            'adrFact' => $adrFact,
            'usersId' => $usersId,
            'factId' => $factId,
            'prod' =>$prod,
            'commandes' => $commandeRepository->facture($id),

            // 'panier' => $repo->findBy(['panier_com' => $id]),

        ]);
    }



    #[Route('/new', name: 'app_commande_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commande = new Commande();
        $form = $this->createForm(Commande1Type::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande_crud/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_crud_show', methods: ['GET'])]
    public function show(Commande $commande): Response
    {
        return $this->render('commande_crud/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commande_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Commande1Type::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande_crud/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_crud_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commande_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_crud_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commande_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commande_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>

    {{ include('commande_crud/_delete_form.html.twig') }}
{% endblock %}

templates/commande_crud/facture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture{% endblock %}

{% block body %}

<div class='container'>
        <div class='row'>    
            <img src="/images/logo.png" class="logo col-4"> 
                <div class='col-6 my-auto'>
                    <div>Facture N° {{ factId }}</div>
                    <div>Commande N°  {{ comId }}  du  {{ createAt ? createAt|date('Y-m-d') : '' }}</div>
                    <div>Date : {{ dateFact ? dateFact|date('Y-m-d') : '' }}</div>
                    
                </div>
                <div> Client : n°{{ adrLivr.Id }}, {{ adrLivr.AdrNom}} {{ adrLivr.AdrPrenom}}  </div>
        <div> Adresse de livraison : {{ adrLivr.Adresse }}, {{ adrLivr.AdrCodePostal }}, {{adrLivr.AdrVille}}, {{ adrLivr.AdrPays}} </div>
            <div> {{ adrLivr.AdrTelephone }}, {{ adrLivr.AdrEmail }}  </div>
            </div>
            {# Adresse de facturation : {{ adrFact.AdrNom }} {{ adrFact.AdrPrenom }} , {{ adrFact.AdrRue }} , {{ adrFact.AdrCodePostal }} {{ adrFact.AdrVille }} {{ adrFact.AdrPays }} #}
        </div>
        <div class='mt-5'> Description de la commande </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>REF.</th>
                <th>DESIGNATION</th>
                <th>P U</th>
                <th>Quantité</th>
                <th>Total HT</th>
                <th>TVA</th>
                <th>Total TVA</th>
                <th>Frais de port</th>
                <th>Total TTC</th>
                {# <th>Adresse</th>
                <th>Adresse de facturation</th>
                <th>Numero client</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Date commande</th> #}
                {#  <th>Com_adresse_facturation</th>
                <th>Com_isPaid</th>
                <th>Com_moyen_paiement</th>
                <th>Com_stripe_session_id</th>
                <th>Com_paypal_id</th>
                <th>actions</th> #}
            </tr>
                </thead>

                <tbody> 
                {# <pre>
                    {{ dump(panier) }}
                </pre> #}
        {% for commande in commandes %}
            <tr>
            <td>{{ commande.c_id }}</td>
            <td>{{ commande.p_nom }}</td>
                <td>{{ commande.p_prix| format_currency('EUR', locale='fr') }}</td>
                <td>{{ commande.p_quantite }}</td>
                <td>{{ commande.p_total1| format_currency('EUR', locale='fr') }}</td>
                <td>{{ (commande.p_total1 * 0.2)| format_currency('EUR', locale='fr')}}</td>
                <td>{{(commande.p_total1 + (commande.p_total1 * 0.2))| format_currency('EUR', locale='fr')}}</td>
                <td> {{ (commande.c_t)}} </td> 
                <td>{{(commande.p_total1 + (commande.p_total1 * 0.2) + (commande.c_t))| format_currency('EUR', locale='fr')}}</td>

                 {# <td>{{ commande.c_adLiv }}</td>
                <td>{{ commande.c_adFac }}</td>
                <td>{{ commande.user_id }}</td>
                <td>{{ commande.user_email }}</td>
                <td>{{ commande.user_tel }}</td>
                <td>{{ commande.c_date ? commande.c_date|date('Y-m-d') : '' }}</td> 
                {<td>{{ commande.c_date ? commande.c_date|date('Y-m-d H:i:s') : '' }}</td> 
                 <td>{{ commande.p_SousTotal }}</td>  #}
                {# <td>{{ commande.comAdresseFacturation }}</td>
                <td>{{ commande.comIsPaid ? 'Yes' : 'No' }}</td>
                <td>{{ commande.comMoyenPaiement }}</td>
                <td>{{ commande.comStripeSessionId }}</td>
                <td>{{ commande.comPaypalId }}</td> #}
               
  {# {% else %} 
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
           {% for total in totals %}
           <td>Transporteur</td>
           <td>{{ total.p_tra }} </td>
           <td> {{ total.p_fdp | format_currency('EUR', locale='fr') }} </td>
           <td> </td>
            <td> {{ total.p_fdp | format_currency('EUR', locale='fr')}} </td>
             <td colspan="2"></td>
                          {% endfor %}
        </tbody>
          <tfoot>
          {% for total in totals %}
                        <tr>
                         <td colspan="2"></td>
                            <td colspan="2">Total</td>
                            
                            <td> {{ total.p_total | format_currency('EUR', locale='fr')}} </td>
                            <td> {{ ((total.p_total - total.p_fdp)  * 0.2) | format_currency('EUR', locale='fr') }} </td>
                            <td> {{ (((total.p_total - total.p_fdp)  * 0.2) + (total.p_total))| format_currency('EUR', locale='fr') }} </td>
                        </tr>
                          {% endfor %}
          </tfoot>
    </table> #} 

    {# <a href="{{ path('app_commande_crud_new') }}">Create new</a> #}
    {# <p>Solde payable sous « délai de paiement » à réception de facture, par « mode de paiement ».</p>
    <div>Pénalité de retard au taux annuel de « nombre » % </div>
<div>En cas de retard de paiement, application d’une indemnité forfaitaire pour frais de recouvrement de 50 euros (article D. 441-5 du code du commerce).</div>
   <div class='mt-5'> HairCompany </div>
    <div> SA au capital de  </div>
    </div>  #}
    {% endfor %}
{% endblock %} 

templates/commande_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom du transporteur</th>
                <th>Prix du transport</th>
                <th>Adresse de livraison</th>
                <th>Payé</th>
                <th>Mode de paiement</th>
                {# <th>Reference</th> #}
                {# <th>Identifiant de la session</th>
                <th>Identifiant paypal</th> #}
                <th>Date de commande</th>
                <th>Adresse de facturation</th>
                <th>Date de facturation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.transporteurNom }}</td>
                <td>{{ commande.transporteurPrix }}</td>
                <td>{{ commande.livraison }}</td>
                <td>{{ commande.isPaid ? 'Yes' : 'No' }}</td>
                <td>{{ commande.methode }}</td>
                {# <td>{{ commande.reference }}</td> #}
                {# <td>{{ commande.stripeSessionId }}</td>
                <td>{{ commande.paypalCommandeId }}</td> #}
                <td>{{ commande.CreateAt ? commande.CreateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.adrFact }}</td>
                <td>{{ commande.CreateAt ? commande.CreateAt|date('Y-m-d H:i:s T') : '' }}</td>
                <td>
                    <a href="{{ path('app_commande_crud_show', {'id': commande.id}) }}">Afficher</a>
                    <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_crud_new') }}">Créer un nouveau</a>
{% endblock %}

templates/commande_crud/mycommande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom du transporteur</th>
                <th>Prix du transport</th>
                <th>Adresse de livraison</th>
                <th>Payé</th>
                <th>Mode de paiement</th>
                {# <th>Reference</th> #}
                {# <th>Identifiant de la session</th> #}
                {# <th>Identifiant paypal</th> #}
                <th>Date de commande</th>
                <th>Adresse de facturation</th>
                <th>Date de facturation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.transporteurNom }}</td>
                <td>{{ commande.transporteurPrix }}</td>
                <td>{{ commande.livraison }}</td>
                <td>{{ commande.isPaid ? 'Yes' : 'No' }}</td>
                <td>{{ commande.methode }}</td>
                {# <td>{{ commande.reference }}</td> #}
                {# <td>{{ commande.stripeSessionId }}</td> #}
                {# <td>{{ commande.paypalCommandeId }}</td> #}
                <td>{{ commande.CreateAt ? commande.CreateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.adrFact }}</td>
                <td>{{ commande.CreateAt ? commande.CreateAt|date('Y-m-d H:i:s T') : '' }}</td>
                <td>
                    <a href="{{ path('app_commande_crud_show', {'id': commande.id}) }}">Afficher</a>
                    <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">Modifier</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/commande_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande_crud/_form.html.twig') }}

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>
{% endblock %}

templates/commande_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>TransporteurNom</th>
                <td>{{ commande.transporteurNom }}</td>
            </tr>
            <tr>
                <th>TransporteurPrix</th>
                <td>{{ commande.transporteurPrix }}</td>
            </tr>
            <tr>
                <th>Livraison</th>
                <td>{{ commande.livraison }}</td>
            </tr>
            <tr>
                <th>IsPaid</th>
                <td>{{ commande.isPaid ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Methode</th>
                <td>{{ commande.methode }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ commande.reference }}</td>
            </tr>
            <tr>
                <th>StripeSessionId</th>
                <td>{{ commande.stripeSessionId }}</td>
            </tr>
            <tr>
                <th>PaypalCommandeId</th>
                <td>{{ commande.paypalCommandeId }}</td>
            </tr>
            <tr>
                <th>CreateAt</th>
                <td>{{ commande.CreateAt ? commande.CreateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Adr_fact</th>
                <td>{{ commande.adrFact }}</td>
            </tr>
            <tr>
                <th>Date_fact</th>
                <td>{{ commande.dateFact ? commande.dateFact|date('Y-m-d H:i:s T') : '' }}</td>
            </tr>
            <tr>
                <th>Com_fact_id</th>
                <td>{{ commande.comFactId }}</td>
            </tr>
            <tr>
                <th>Facture_total_ttc</th>
                <td>{{ commande.factureTotalTtc }}</td>
            </tr>
            <tr>
                <th>Facture_total_ht</th>
                <td>{{ commande.factureTotalHt }}</td>
            </tr>
            <tr>
                <th>Facture_tva</th>
                <td>{{ commande.factureTva }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>

    <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a>

    {{ include('commande_crud/_delete_form.html.twig') }}
{% endblock %}